resources:
  - url: http://127.0.0.1:5000/swipe-glance-card.js
    type: module
  - url: http://127.0.0.1:5000/card-mod.js
    type: module
  - url: http://127.0.0.1:5000/auto-entities.js
    type: module
views:
  - cards:
      - type: custom:swipe-glance-card
        title: Swipe Glance Card 1
        style: |
          ha-card {
            font-variant: small-caps;
          }
          .card-header {
            font-size: 16px;
          }
        entities:
          - entity: sun.sun
            options:
              style: |
                :host {
                  --paper-item-icon-color: green
                }
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
      - type: custom:swipe-glance-card
        entities:
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
      - type: custom:swipe-glance-card
        title: Swipe Glance Card 3
        entities:
          - entity: sun.sun
            name: moon
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
            icon: mdi:star
      - type: "custom:auto-entities"
        card:
          swiper_parameters:
            navigation:
              nextEl: ".swiper-button-next"
              prevEl: ".swiper-button-prev"
          title: Swipe Glance Card 4
          type: "custom:swipe-glance-card"
        filter:
          template: |
            {{ states|map(attribute='entity_id')|join('\n') }}
      - type: "custom:auto-entities"
        card:
          swiper_parameters:
            pagination:
              el: ".swiper-pagination"
          title: Swipe Glance Card 5
          type: "custom:swipe-glance-card"
        filter:
          include:
            - domain: binary_sensor
            - domain: climate
            - domain: cover
        sort:
          method: name
      - type: "custom:auto-entities"
        card:
          swiper_parameters:
            scrollbar:
              el: ".swiper-scrollbar"
              dynamicBullets: true
          title: Swipe Glance Card 6
          type: "custom:swipe-glance-card"
        filter:
          include:
            - domain: binary_sensor
              options:
                style: |
                  :host {
                    --paper-item-icon-color: green
                  }
            - domain: climate
              options:
                style: |
                  :host {
                    --paper-item-icon-color: green
                  }
            - domain: cover
              options:
                style: |
                  :host {
                    --paper-item-icon-color: green
                  }
        sort:
          method: name
      - type: "custom:auto-entities"
        card:
          swiper_parameters:
            scrollbar:
              el: ".swiper-scrollbar"
              dynamicBullets: true
          title: Swipe Glance Card 7
          type: glance
        filter:
          include:
            - domain: binary_sensor
              options:
                style: |
                  :host {
                    --paper-item-icon-color: green
                  }
            - domain: climate
              options:
                style: |
                  :host {
                    --paper-item-icon-color: green
                  }
            - domain: cover
              options:
                style: |
                  :host {
                    --paper-item-icon-color: green
                  }
        sort:
          method: name
