resources:
  - url: http://127.0.0.1:5000/swipe-glance-card.js
    type: module
views:
  - cards:
      - type: custom:swipe-glance-card
        title: Swipe Glance Card 1
        entities:
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
      - type: custom:swipe-glance-card
        entities:
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
      - type: custom:swipe-glance-card
        title: Swipe Glance Card 3
        entities:
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
          - entity: sun.sun
